{{- range $name, $keyValues := .Values.sealedsecrets }}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $name }}
spec:
  encryptedData:
  {{- range $key, $values := $keyValues }}
    {{ printf "%s: %s" $key $values }}
  {{- end }}
{{- end }}
