traefik:
  namespaceOverride: traefik
  ports:
    web:
      port: 80
    websecure:
      port: 443
  deployment:
    replicas: 3
  service:
    annotations:
      metallb.universe.tf/address-pool: metallb
      metallb.universe.tf/allow-shared-ip: "metallb-shared"
  volumes:
  - name: "config"
    mountPath: "/etc/traefik"
    type: configMap
  - name: certs
    mountPath: "/certs"
    readOnly: true
    type: secret
    items:
    - key: tls.key
      path: tls.key
    - key: tls.crt
      path: tls.crt
  additionalArguments:
  - "--providers.file.filename=/etc/traefik/traefik.yaml"
  - "--providers.file.filename=/etc/traefik/middlewares.yaml"
  - "--providers.file.filename=/etc/traefik/tls.yaml"
  ingressRoute:
    dashboard:
      enabled: false

sealed-secrets: {}
